#!/usr/bin/env -S pkgx +mash bash

usage() {
  echo "usage: mash pkgx/cache <ls|upgrade|prune>"
}

cmd="$1"
shift

case "$cmd" in
neophile|neophilia|neophiliac)
  exec pkgx mash "pkgx/cache+upgrade" "$@";;
ls|cache|prune)
  exec pkgx mash "pkgx/cache+$cmd" "$@";;
--help)
  usage;;
*)
  usage
  exit 64;
esac
