#!/bin/sh

usage() {
  echo "usage: mash pkgx/cache <ls|upgrade|prune>"
}

cmd="$1"
shift

case "$cmd" in
neophile|neophilia|neophiliac)
  exec pkgx mash "pkgx/upgrade" "$@";;
ls|upgrade|prune)
  exec pkgx mash "pkgx/$cmd" "$@";;
--help)
  usage;;
*)
  usage
  exit 64;
esac
